### ISSUE TITLE
Map generation exceptions

### ISSUE THREAD

**Issue by Kot1que** [Mezy/UhcCore#18]
Got many exceptions during map generation. They seem to appear randomly. However, server starts after that without problems. 

I tried to run server on 2 and 8 core cpu server (needed faster map generation) and didn't see such exceptions on 2 core cpu server.

I'm using the latest plugin version 1.15.9 and the latest spigot 1.15.2 build.

Log:
```
[14:37:19] [Server thread/INFO]: [UhcCore] Loading map NORMAL 17.2% - 2695.0/15625.0 chunks loaded
[14:37:29] [Server thread/FATAL]: Failed to schedule unload callback for chunk [-40, 41]
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Already queued
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) [?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) [?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) [?:?]
	at net.minecraft.server.v1_15_R1.PlayerChunk.a(PlayerChunk.java:293) [spigot.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.ChunkMapDistance.a(ChunkMapDistance.java:107) [spigot.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:252) [spigot.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.purgeUnload(ChunkProviderServer.java:324) [spigot.jar:git-Spigot-6de3d4b-fc24934]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.unloadChunk0(CraftWorld.java:397) [spigot.jar:git-Spigot-6de3d4b-fc24934]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.unloadChunk(CraftWorld.java:373) [spigot.jar:git-Spigot-6de3d4b-fc24934]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.unloadChunk(CraftWorld.java:368) [spigot.jar:git-Spigot-6de3d4b-fc24934]
	at com.gmail.val59000mc.maploader.MapLoader$1$1RunnableWithParameter.run(MapLoader.java:270) [UhcCore-1.15.9.jar:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot.jar:git-Spigot-6de3d4b-fc24934]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot.jar:git-Spigot-6de3d4b-fc24934]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: Already queued
	at net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.execute(PlayerChunkMap.java:86) ~[spigot.jar:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.PlayerChunk.lambda$4(PlayerChunk.java:296) ~[spigot.jar:git-Spigot-6de3d4b-fc24934]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) ~[?:?]
	... 17 more
[14:37:31] [Server thread/INFO]: [UhcCore] Loading map NORMAL 18.4% - 2885.0/15625.0 chunks loaded
```

**Comment by Mezy** [comment]
Did you reload your server by any chance?

**Comment by Kot1que** [comment]
No. The server was never restarted\reloaded during the game or starting phase. As I said, this errors seem not to affect anything. Within about 10 games we haven't seen any broken chunks or something wrong.

I tried entering "reload" command during map pregeneration on my pc and the error occured.

Also if I happen to play once more, I will try to provide more information.

**Comment by Mezy** [comment]
Fixed for next update, thanks for reporting!

**Comment by Us3rNqmed** [comment]
I Also got this issue.
I Cant fix it in anyway.

**Comment by Mezy** [comment]
> I Also got this issue.
> I Cant fix it in anyway.

What version of the plugin are you using?
Also please attach the errors your getting. These exact errors are no-longer possible on the latest version.
