### ISSUE TITLE
1.17 Issue upon Plugin Load with BiomeMapping

### ISSUE THREAD

**Issue by Wolfst0rm** [Mezy/UhcCore#90]
```[10:21:26] [Server thread/INFO]: [UhcCore] Enabling UhcCore v1.19.3
[10:21:26] [Server thread/INFO]: [UhcCore] 1.17 Server detected!
[10:21:26] [Server thread/WARN]: [UhcCore] WorldEdit plugin not found, there will be no support of schematics.
[10:21:26] [Server thread/INFO]: [UhcCore] Hooked with Vault plugin.
[10:21:26] [Server thread/WARN]: [UhcCore] ProtocolLib plugin not found.
[10:21:26] [Server thread/INFO]: [UhcCore] Start loading kits
[10:21:26] [Server thread/INFO]: [UhcCore] Loaded 0 kits
[10:21:26] [Server thread/INFO]: [UhcCore] Loading banned crafts list
[10:21:26] [Server thread/INFO]: [UhcCore] Loading custom crafts
[10:21:27] [Server thread/WARN]: [UhcCore] Task #30 for UhcCore v1.19.3 generated an exception
java.lang.RuntimeException: Version v1_17_R1 is not supported!
        at com.pieterdebot.biomemapping.BiomeMappingAPI.getWrapper(BiomeMappingAPI.java:83) ~[?:?]
        at com.pieterdebot.biomemapping.BiomeMappingAPI.<init>(BiomeMappingAPI.java:25) ~[?:?]
        at com.gmail.val59000mc.maploader.MapLoader.replaceOceanBiomes(MapLoader.java:357) ~[?:?]
        at com.gmail.val59000mc.maploader.MapLoader.loadWorlds(MapLoader.java:70) ~[?:?]
        at com.gmail.val59000mc.game.GameManager.loadNewGame(GameManager.java:241) ~[?:?]
        at com.gmail.val59000mc.UhcCore.lambda$onEnable$0(UhcCore.java:25) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:3159-Spigot-f773da8-887bc05]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:3159-Spigot-f773da8-887bc05]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1252) ~[server.jar:3159-Spigot-f773da8-887bc05]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[server.jar:3159-Spigot-f773da8-887bc05]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[server.jar:3159-Spigot-f773da8-887bc05]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027) ~[server.jar:3159-Spigot-f773da8-887bc05]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3159-Spigot-f773da8-887bc05]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

Version of Spigot: 3159-Spigot-f773da8-887bc05 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
Full Log: https://paste.md-5.net/zerosatiji

**Comment by MadeByIToncek** [comment]
Fixed in 1.19.4
